baseURL = 'https://anbarasan.in/'
languageCode = 'en-us'
title = 'Anbarasan'
enableRobotsTXT = true
theme = 'PaperMod'

[params]
  env = 'production'
  author = 'அன்பரசன் (Anbarasan)'
  disableHomePosts = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowToc = true

[params.profileMode]
  enabled = false

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = '~/projects'
  url = '/projects/'
  weight = 1

[[menu.main]]
  name = '~/blog'
  url = '/blog/'
  weight = 2

[[menu.main]]
  name = "~/rpg"
  url = "/rpg/"
  weight = 3

[[menu.main]]
  name = '~/contact'
  url = '/contact/'
  weight = 4
  
[[menu.main]]
  name = '~/about'
  url = '/about/'
  weight = 5
