baseURL = 'https://anbarasan.in/'
languageCode = 'en-us'
title = 'Anbarasan'
enableRobotsTXT = true
theme = 'PaperMod'

[params]
  env = 'production'
  author = 'Anbarasan'

[[menu.main]]
  name = '~/projects'
  url = '/projects/'
  weight = 1

[[menu.main]]
  name = '~/blog'
  url = '/posts/'
  weight = 2

[[menu.main]]
  name = '~/contact'
  url = '/contact/'
  weight = 3
  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4
